package model;

public class Countries
{
	public static String[] LIST =
	{
		"Afghanistan",
		"Albanien",
		"Algeriet",
		"Amerikanska Samoa",
		"Andorra",
		"Angola",
		"Anguilla",
		"Antigua & Barbuda",
		"Argentina",
		"Armenien",
		"Aruba",
		"Australien",
		"Azerbajdzjan",
		"Bahamas",
		"Bahrain",
		"Bangladesh",
		"Barbados",
		"Belarus",
		"Belgien",
		"Belize",
		"Benin",
		"Bermuda",
		"Bhutan",
		"Bolivia",
		"Bosnien och Herzegovina",
		"Botswana",
		"Brasilien",
		"Brunei",
		"Bulgarien",
		"Burkina Faso",
		"Burma",
		"Burundi",
		"Caymanöarna",
		"Centralafrikanska republiken",
		"Colombia",
		"Cooköarna",
		"Costa Rica",
		"Cypern",
		"Danmark",
		"Demokratiska republiken Kongo",
		"Djibouti",
		"Dominica",
		"Dominikanska Republiken",
		"Ecuador",
		"Egypten",
		"Ekvatorialguinea",
		"Elfenbenskusten",
		"El Salvador",
		"Eritrea",
		"Estland",
		"Etiopien",
		"Falklandsöarna",
		"Färöarna",
		"Fiji",
		"Fillipinerna",
		"Finland",
		"Förenade Arabemirater",
		"Frankrike",
		"Franska Guyana",
		"Franska Polynesien",
		"Gabon",
		"Gambia",
		"Georgien",
		"Ghana",
		"Gibraltar",
		"Grekland",
		"Grenada",
		"Grönland",
		"Guadeloupe",
		"Guam",
		"Guatemala",
		"Guernsey",
		"Guinea",
		"Guinea-Bissau",
		"Guyana",
		"Haiti",
		"Honduras",
		"Chile",
		"Indien",
		"Indonesien",
		"Irak",
		"Iran",
		"Irland",
		"Island",
		"Isle of Man",
		"Israel",
		"Italien",
		"Jamaica",
		"Japan",
		"Jemen",
		"Jersey",
		"Jordanien",
		"Kambodja",
		"Kamerun",
		"Kanada",
		"Kap Verde",
		"Kazakhstan",
		"Kenya",
		"Kina",
		"Kiribati",
		"Kokosöarna",
		"Komorerna",
		"Kroatien",
		"Kuba",
		"Kuwait",
		"Kyrgyzstan",
		"Laos",
		"Lesotho",
		"Lettland",
		"Libanon",
		"Liberia",
		"Libyen",
		"Liechtenstein",
		"Litauen",
		"Luxemburg",
		"Madagaskar",
		"Makedonien",
		"Malawi",
		"Malaysia",
		"Maldiverna",
		"Mali",
		"Malta",
		"Marocko",
		"Marshallöarna",
		"Martinique",
		"Mauretanien",
		"Mauritius",
		"Mexico",
		"Mikronesien",
		"Moçambique",
		"Moldavien",
		"Monaco",
		"Mongoliet",
		"Montenegro",
		"Montserrat",
		"Namibia",
		"Nauru",
		"Nederländerna",
		"Nederländska Antillerna",
		"Nepal",
		"Nicaragua",
		"Niger",
		"Nigeria",
		"Nordkorea",
		"Nord-Makedonien",
		"Nordmarianerna",
		"Norge",
		"Nya Kaledonien",
		"Nya Zeland",
		"Oman",
		"Österrike",
		"Östtimor",
		"Pakistan",
		"Palau",
		"Panama",
		"Papua Nya Guinea",
		"Paraguay",
		"Peru",
		"Pitcairnöarna",
		"Polen",
		"Portugal",
		"Puerto Rico",
		"Qatar",
		"Republiken Kongo",
		"Resten av världen",
		"Réunion",
		"Rumänien",
		"Rwanda",
		"Ryssland",
		"Saint Kitts och Nevis",
		"Saint Lucia",
		"Saint-Pierre och Miquelon",
		"Saint Vincent och Grenadinerna",
		"Salomonöarna",
		"Samoa",
		"Sankta Helena",
		"San Marino",
		"São Tomé och Príncipe",
		"Saudiarabien",
		"Senegal",
		"Serbien",
		"Seychellerna",
		"Schweiz",
		"Sierra Leone",
		"Singapor",
		"Slovakien",
		"Slovenien",
		"Somalia",
		"Spanien",
		"Sri Lanka",
		"Storbritannien",
		"Sudan",
		"Surinam",
		"Sverige",
		"Swaziland",
		"Sydafrika",
		"Sydkorea",
		"Syrien",
		"Taiwan",
		"Tajikistan",
		"Tanzania",
		"Thailand",
		"Tchad",
		"Tjeckien",
		"Togo",
		"Tonga",
		"Trinidad och Tobago",
		"Tunisien",
		"Turkiet",
		"Turkmenistan",
		"Tuvalu",
		"Tyskland",
		"Uganda",
		"Ukraina",
		"Ungern",
		"Uruguay",
		"USA",
		"Uzbekistan",
		"Vanuatu",
		"Västsahara",
		"Vatikanstaten",
		"Venezuela",
		"Vietnam",
		"Vitryssland",
		"Zambia",
		"Zimbabwe"
	};
}
